// <auto-generated />
using System.Windows.Forms;

namespace FacebookChecker
{
    partial class MainForm
    {
        private TextBox txtListFile;
        private TextBox txtCookiesFile;
        private TextBox txtProxiesFile;
        private Button btnBrowseList;
        private Button btnBrowseCookies;
        private Button btnBrowseProxies;
        private NumericUpDown numBatch;
        private NumericUpDown numDelay;
        private NumericUpDown numRetries;
        private Label lblBatch;
        private Label lblDelay;
        private Label lblRetries;
        private Button btnStart;
        private Button btnStop;
        private ProgressBar progressBar;
        private TextBox logBox;
        private Label lblStatus;
        private Button btnOpenLive;
        private Button btnOpenDead;
        private CheckBox chkJitter;

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.txtListFile = new TextBox();
            this.txtCookiesFile = new TextBox();
            this.txtProxiesFile = new TextBox();
            this.btnBrowseList = new Button();
            this.btnBrowseCookies = new Button();
            this.btnBrowseProxies = new Button();
            this.numBatch = new NumericUpDown();
            this.numDelay = new NumericUpDown();
            this.numRetries = new NumericUpDown();
            this.lblBatch = new Label();
            this.lblDelay = new Label();
            this.lblRetries = new Label();
            this.btnStart = new Button();
            this.btnStop = new Button();
            this.btnOpenLive = new Button();
            this.btnOpenDead = new Button();
            this.progressBar = new ProgressBar();
            this.logBox = new TextBox();
            this.lblStatus = new Label();
            this.chkJitter = new CheckBox();

            ((System.ComponentModel.ISupportInitialize)(this.numBatch)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numDelay)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numRetries)).BeginInit();
            this.SuspendLayout();
            // 
            // txtListFile
            // 
            this.txtListFile.Location = new System.Drawing.Point(12, 12);
            this.txtListFile.Name = "txtListFile";
            this.txtListFile.PlaceholderText = "Path list.txt";
            this.txtListFile.Size = new System.Drawing.Size(360, 23);
            // 
            // txtCookiesFile
            // 
            this.txtCookiesFile.Location = new System.Drawing.Point(12, 41);
            this.txtCookiesFile.Name = "txtCookiesFile";
            this.txtCookiesFile.PlaceholderText = "Path cookies.txt (optional)";
            this.txtCookiesFile.Size = new System.Drawing.Size(360, 23);
            // 
            // txtProxiesFile
            // 
            this.txtProxiesFile.Location = new System.Drawing.Point(12, 70);
            this.txtProxiesFile.Name = "txtProxiesFile";
            this.txtProxiesFile.PlaceholderText = "Path proxies.txt (optional)";
            this.txtProxiesFile.Size = new System.Drawing.Size(360, 23);
            // 
            // btnBrowseList
            // 
            this.btnBrowseList.Location = new System.Drawing.Point(378, 12);
            this.btnBrowseList.Name = "btnBrowseList";
            this.btnBrowseList.Size = new System.Drawing.Size(75, 23);
            this.btnBrowseList.Text = "Browse";
            this.btnBrowseList.UseVisualStyleBackColor = true;
            this.btnBrowseList.Click += new System.EventHandler(this.btnBrowseList_Click);
            // 
            // btnBrowseCookies
            // 
            this.btnBrowseCookies.Location = new System.Drawing.Point(378, 41);
            this.btnBrowseCookies.Name = "btnBrowseCookies";
            this.btnBrowseCookies.Size = new System.Drawing.Size(75, 23);
            this.btnBrowseCookies.Text = "Browse";
            this.btnBrowseCookies.UseVisualStyleBackColor = true;
            this.btnBrowseCookies.Click += new System.EventHandler(this.btnBrowseCookies_Click);
            // 
            // btnBrowseProxies
            // 
            this.btnBrowseProxies.Location = new System.Drawing.Point(378, 70);
            this.btnBrowseProxies.Name = "btnBrowseProxies";
            this.btnBrowseProxies.Size = new System.Drawing.Size(75, 23);
            this.btnBrowseProxies.Text = "Browse";
            this.btnBrowseProxies.UseVisualStyleBackColor = true;
            this.btnBrowseProxies.Click += new System.EventHandler(this.btnBrowseProxies_Click);
            // 
            // numBatch
            // 
            this.numBatch.Location = new System.Drawing.Point(66, 103);
            this.numBatch.Minimum = 1;
            this.numBatch.Maximum = 200;
            this.numBatch.Value = 10;
            this.numBatch.Name = "numBatch";
            this.numBatch.Size = new System.Drawing.Size(60, 23);
            // 
            // numDelay
            // 
            this.numDelay.Location = new System.Drawing.Point(210, 103);
            this.numDelay.Minimum = 0;
            this.numDelay.Maximum = 60;
            this.numDelay.Value = 2;
            this.numDelay.Name = "numDelay";
            this.numDelay.Size = new System.Drawing.Size(60, 23);
            // 
            // numRetries
            // 
            this.numRetries.Location = new System.Drawing.Point(360, 103);
            this.numRetries.Minimum = 0;
            this.numRetries.Maximum = 10;
            this.numRetries.Value = 2;
            this.numRetries.Name = "numRetries";
            this.numRetries.Size = new System.Drawing.Size(50, 23);
            // 
            // lblBatch
            // 
            this.lblBatch.AutoSize = true;
            this.lblBatch.Location = new System.Drawing.Point(12, 105);
            this.lblBatch.Text = "Batch";
            // 
            // lblDelay
            // 
            this.lblDelay.AutoSize = true;
            this.lblDelay.Location = new System.Drawing.Point(162, 105);
            this.lblDelay.Text = "Delay (s)";
            // 
            // lblRetries
            // 
            this.lblRetries.AutoSize = true;
            this.lblRetries.Location = new System.Drawing.Point(280, 105);
            this.lblRetries.Text = "Retries";
            // 
            // chkJitter
            // 
            this.chkJitter.AutoSize = true;
            this.chkJitter.Location = new System.Drawing.Point(420, 103);
            this.chkJitter.Text = "Random jitter";
            this.chkJitter.Checked = true;
            // 
            // btnStart
            // 
            this.btnStart.Location = new System.Drawing.Point(12, 139);
            this.btnStart.Name = "btnStart";
            this.btnStart.Size = new System.Drawing.Size(75, 28);
            this.btnStart.Text = "Start";
            this.btnStart.UseVisualStyleBackColor = true;
            this.btnStart.Click += new System.EventHandler(this.btnStart_Click);
            // 
            // btnStop
            // 
            this.btnStop.Location = new System.Drawing.Point(93, 139);
            this.btnStop.Name = "btnStop";
            this.btnStop.Size = new System.Drawing.Size(75, 28);
            this.btnStop.Text = "Stop";
            this.btnStop.Enabled = false;
            this.btnStop.UseVisualStyleBackColor = true;
            this.btnStop.Click += new System.EventHandler(this.btnStop_Click);
            // 
            // btnOpenLive
            // 
            this.btnOpenLive.Location = new System.Drawing.Point(312, 139);
            this.btnOpenLive.Name = "btnOpenLive";
            this.btnOpenLive.Size = new System.Drawing.Size(66, 28);
            this.btnOpenLive.Text = "Open LIVE";
            this.btnOpenLive.Enabled = false;
            this.btnOpenLive.UseVisualStyleBackColor = true;
            this.btnOpenLive.Click += new System.EventHandler(this.btnOpenLive_Click);
            // 
            // btnOpenDead
            // 
            this.btnOpenDead.Location = new System.Drawing.Point(384, 139);
            this.btnOpenDead.Name = "btnOpenDead";
            this.btnOpenDead.Size = new System.Drawing.Size(69, 28);
            this.btnOpenDead.Text = "Open DEAD";
            this.btnOpenDead.Enabled = false;
            this.btnOpenDead.UseVisualStyleBackColor = true;
            this.btnOpenDead.Click += new System.EventHandler(this.btnOpenDead_Click);
            // 
            // progressBar
            // 
            this.progressBar.Location = new System.Drawing.Point(12, 175);
            this.progressBar.Name = "progressBar";
            this.progressBar.Size = new System.Drawing.Size(501, 16);
            // 
            // lblStatus
            // 
            this.lblStatus.AutoSize = true;
            this.lblStatus.Location = new System.Drawing.Point(12, 194);
            this.lblStatus.Text = "LIVE: 0 | DEAD: 0 | ERROR: 0";
            // 
            // logBox
            // 
            this.logBox.Location = new System.Drawing.Point(12, 220);
            this.logBox.Multiline = true;
            this.logBox.ScrollBars = ScrollBars.Vertical;
            this.logBox.ReadOnly = true;
            this.logBox.Name = "logBox";
            this.logBox.Size = new System.Drawing.Size(501, 240);
            // 
            // MainForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(525, 475);
            this.Controls.Add(this.txtListFile);
            this.Controls.Add(this.txtCookiesFile);
            this.Controls.Add(this.txtProxiesFile);
            this.Controls.Add(this.btnBrowseList);
            this.Controls.Add(this.btnBrowseCookies);
            this.Controls.Add(this.btnBrowseProxies);
            this.Controls.Add(this.numBatch);
            this.Controls.Add(this.numDelay);
            this.Controls.Add(this.numRetries);
            this.Controls.Add(this.lblBatch);
            this.Controls.Add(this.lblDelay);
            this.Controls.Add(this.lblRetries);
            this.Controls.Add(this.chkJitter);
            this.Controls.Add(this.btnStart);
            this.Controls.Add(this.btnStop);
            this.Controls.Add(this.btnOpenLive);
            this.Controls.Add(this.btnOpenDead);
            this.Controls.Add(this.progressBar);
            this.Controls.Add(this.lblStatus);
            this.Controls.Add(this.logBox);
            this.FormBorderStyle = FormBorderStyle.FixedSingle;
            this.MaximizeBox = false;
            this.Name = "MainForm";
            this.StartPosition = FormStartPosition.CenterScreen;
            this.Text = "Facebook Reviews Checker";
            ((System.ComponentModel.ISupportInitialize)(this.numBatch)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numDelay)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numRetries)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
    }
}
